### ISSUE TITLE
Build and publish wheels for python 3.11

### ISSUE THREAD

**Issue by aris-aiven** [intake/python-snappy#124]
Hi there, it would be great to have python 3.11 compatibility.

**Comment by gertjanwytynck** [comment]
Anyone got this one working on python 3.11.2?

**Comment by martindurant** [comment]
I wonder what the use case is now for this library? Would people consider using `cramjam` instead?

**Comment by gertjanwytynck** [comment]
I need to use it for pymongo-compression..

I see this PR, when will it be merged?
https://github.com/andrix/python-snappy/pull/125

**Comment by cbini** [comment]
@martindurant thanks for recommending cramjam. Unfortunately, I can't use that because fastavro depends exclusively on this library for using the snappy codec. It's probably possible to rewrite my avro read/write code to use the vanilla avro package, but that's a much bigger project.

**Comment by martindurant** [comment]
@milesgranger , there seems little point in maintaining this snappy, and there are things about the build system I don't understand. Do you think we can make this a compatibility pseudo-package that just calls cramjam? Later, we can introduce a deprecation on import and eventually retire this package.

**Comment by milesgranger** [comment]
I think cramjam has been in use long enough to have exposed any egregious warts it might've had and I'm not planning on going anywhere. So would be pleased as pie to continue to support it. :ok_hand:

**Comment by martindurant** [comment]
@milesgranger , the only missing I see is an equivalent to snappy.StreamDecompressor , which is the iterable counterpart to what cramjam.snappy.Compressor does. There is also a StreamCompressor which I think is identical to Compressor. Of course, this should be tested. I doubt either of these gets much use compared to compress/decompress, but it would be nice to support the whole current API.

**Comment by milesgranger** [comment]
Fair point. I'm casually working on some updates for cramjam lately anyway, so might be good to add that to the todo list. :)

**Comment by milesgranger** [comment]
FWIW, [v2.7.0](https://github.com/milesgranger/pyrus-cramjam/releases/tag/v2.7.0) released today has effectively the same StreamDecompressor

**Comment by gliptak** [comment]
#129

**Comment by gliptak** [comment]
please check https://pypi.org/project/python-snappy/0.7.0.dev1/

**Comment by martindurant** [comment]
^ this can be installed with
```
pip install --pre python-snappy
```
or by specifying the exact version desired.

**Comment by aris-aiven** [comment]
Seeing versions `0.7.0` and `0.7.1` are available on PyPi, I'm closing this as completed.
Thanks a lot for your time and effort @martindurant @gliptak and @milesgranger for the awesome library!
