### ISSUE TITLE
Q: How to handle hadoop_snappy?

### ISSUE THREAD

**Issue by dbarrundia-tiger** [intake/python-snappy#137]
Sorry if this is such a silly question. With the new version upgrade to `0.7.1`, is there any recommendation on how to best migrate off `hadoop_snappy`. We used to use the StreamCompressor from `hadoop_snappy`
```
from snappy import hadoop_snappy
compressor = hadoop_snappy.StreamCompressor()
```

**Comment by martindurant** [comment]
I am surprised anyone was using that. The old code can be examined and a new stream de/compressor based on the non-hadoop one made. We don't have any test data to verify the right thing is happening, though.
