### ISSUE TITLE
 RFE: is it possible to start making github releases?🤔

### ISSUE THREAD

**Issue by kloczek** [intake/python-snappy#139]
On create github release entry is created email notification to those whom have set in your repo the web UI Watch->Releases.
gh release can contain additional comments (li changelog) or additional assets like release tar balls (by default it contains only assets from git tag) however all those part are not obligatory.
In simplest variant gh release can be empty because subiekt of the sent email contains git tag name.

I'm asking because my automation process uses those email notifications by trying to make preliminary automated upgrades of building packages, which allows saving some time on maintaining packaging procedures.
Probably other people may be interested to be instantly informed about release new version as well.

Documentation and examples of generate gh releases:
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://cli.github.com/manual/gh_release_upload/
https://github.com/jbms/sphinx-immaterial/pull/282
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/
https://github.com/jbms/sphinx-immaterial/issues/281#issuecomment-1700933026
tox target to publish on pypi and make gh release https://github.com/jaraco/skeleton/blob/928e9a86d61d3a660948bcba7689f90216cc8243/tox.ini#L42-L58

**Comment by martindurant** [comment]
Since the last release, this repo has become a thin shim over `cramjam`. If you want to follow github releases, please follow their's.

**Comment by kloczek** [comment]
https://github.com/intake/python-snappy/releases is empty 😋

**Comment by martindurant** [comment]
Yes it is. Please read again what I have written, and navigate to https://github.com/milesgranger/cramjam/releases

**Comment by martindurant** [comment]
Latest install "build" step
```
$ pip install python-snappy
Collecting python-snappy
  Downloading python_snappy-0.7.1-py3-none-any.whl.metadata (1.3 kB)
Collecting cramjam (from python-snappy)
  Downloading cramjam-2.8.2-cp312-cp312-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl.metadata (4.1 kB)
Downloading python_snappy-0.7.1-py3-none-any.whl (8.6 kB)
Downloading cramjam-2.8.2-cp312-cp312-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl (3.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 12.7 MB/s eta 0:00:00
Installing collected packages: cramjam, python-snappy
Successfully installed cramjam-2.8.2 python-snappy-0.7.1
```
