### ISSUE TITLE
Unable to Compress on PyPy for Python 3.8

### ISSUE THREAD

**Issue by blink1073** [intake/python-snappy#142]
I realize PyPy for Python 3.8 is no longer maintained, but I'm reporting here for completeness.

- Install PyPy for Python 3.8 (`[PyPy 7.3.11 with GCC Apple LLVM 13.1.6 (clang-1316.0.21.2.5)] on darwin`)
- Install `python-snappy` into a virtual environment
- Run the following:

```python
import snappy
snappy.compress(b'123')
...site-packages/snappy/snappy.py", line 78, in compress
    return bytes(_compress(data))
TypeError: 'Buffer' object is not iterable
```

`cramjam.snappy.compress_raw` is returning a `Buffer` object, which can be passed to `bytes()` on other versions of Python, but not this one.

**Comment by martindurant** [comment]
A (much) older version of cramjam should be able to do this, I think, but I don't remember when support for pypy was started.

**Comment by blink1073** [comment]
Thanks!  I confirmed it works when I pin to `cramjam==2.0.2`.
